version: "3"
services:
  api:
    stdin_open: true
    tty: true
    build: .
    ports:
      - "8000:8000"
    command: gunicorn -b :8000 orbquesta:app
  database:
    image: "postgres" # use latest official postgres version
    env_file:
      - database.env # configure postgres
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down

volumes:
  database-data: # named volumes can be managed easier using docker-compose
